### ISSUE TITLE
Alfred 2 Compatibility

### ISSUE THREAD

**Issue by sferrini** [alexhude/alfredworkflow-zsh-calculator#1]
I tried to import this workflow with my copy of Alfred 2 but I get this error:

![screen shot 2016-12-11 at 11 36 30](https://cloud.githubusercontent.com/assets/3370782/21079583/1d22e36c-bf96-11e6-8db0-3ce0db0d3755.png)

Would be cool to add Alfred 2 support.
Thanks!

**Comment by alexhude** [comment]
I have added Alfred2 version. However, I would recommend you to switch to Alfred3 since it is lot more powerful. Also it is unlikely I will support Alfred2 workflows for a long time.

**Comment by alexhude** [comment]
I have added Alfred2 version. However, I would recommend you to switch to Alfred3 since it is lot more powerful. Also it is unlikely I will support Alfred2 workflows for a long time.

**Comment by sferrini** [comment]
I'll definitely consider to upgrade 👍  Thanks!
